/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityDetails: typeof import('./src/components/ui/ActivityDetails.vue')['default']
    ActivityLapsTable: typeof import('./src/components/ui/ActivityLapsTable.vue')['default']
    ActivitySetsTable: typeof import('./src/components/ui/ActivitySetsTable.vue')['default']
    AppNavbar: typeof import('./src/components/navigation/AppNavbar.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BNav: typeof import('bootstrap-vue-next/components/BNav')['BNav']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    CadenceCard: typeof import('./src/components/ui/CadenceCard.vue')['default']
    CalendarWrapper: typeof import('./src/components/ui/CalendarWrapper.vue')['default']
    copy: typeof import('./src/components/ui/SpeedCard copy.vue')['default']
    ElevationCard: typeof import('./src/components/ui/ElevationCard.vue')['default']
    HeartRateCard: typeof import('./src/components/ui/HeartRateCard.vue')['default']
    HRZonesCard: typeof import('./src/components/ui/HRZonesCard.vue')['default']
    IBiChevronDown: typeof import('~icons/bi/chevron-down')['default']
    IBiChevronRight: typeof import('~icons/bi/chevron-right')['default']
    IBiCloudArrowUpFill: typeof import('~icons/bi/cloud-arrow-up-fill')['default']
    IBiFileEarmarkText: typeof import('~icons/bi/file-earmark-text')['default']
    IBiSpeedometer2: typeof import('~icons/bi/speedometer2')['default']
    IBiupload: typeof import('~icons/bi/upload')['default']
    IntensityMinutesCard: typeof import('./src/components/ui/IntensityMinutesCard.vue')['default']
    MetricCard: typeof import('./src/components/ui/MetricCard.vue')['default']
    MinHrCard: typeof import('./src/components/ui/MinHrCard.vue')['default']
    MinHrComponent: typeof import('./src/components/ui/MinHrComponent.vue')['default']
    PowerCard: typeof import('./src/components/ui/PowerCard.vue')['default']
    PowerZonesCard: typeof import('./src/components/ui/PowerZonesCard.vue')['default']
    RadialMetricCard: typeof import('./src/components/ui/RadialMetricCard.vue')['default']
    RouteMap: typeof import('./src/components/ui/RouteMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedCard: typeof import('./src/components/ui/SpeedCard.vue')['default']
    'SpeedCard copy': typeof import('./src/components/ui/SpeedCard copy.vue')['default']
    TrainingEffectCard: typeof import('./src/components/ui/TrainingEffectCard.vue')['default']
    TrainingLoadCard: typeof import('./src/components/ui/TrainingLoadCard.vue')['default']
    TrainingStatusCard: typeof import('./src/components/ui/TrainingStatusCard.vue')['default']
    VO2MaxCard: typeof import('./src/components/ui/VO2MaxCard.vue')['default']
    WeeklyTrainingCard: typeof import('./src/components/ui/WeeklyTrainingCard.vue')['default']
    WeightCard: typeof import('./src/components/ui/WeightCard.vue')['default']
    WeightComponent: typeof import('./src/components/ui/WeightComponent.vue')['default']
  }
}
