/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityDetails: typeof import('./src/components/ui/ActivityDetails.vue')['default']
    AppNavbar: typeof import('./src/components/navigation/AppNavbar.vue')['default']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    CadenceCard: typeof import('./src/components/ui/CadenceCard.vue')['default']
    CalendarWrapper: typeof import('./src/components/ui/CalendarWrapper.vue')['default']
    copy: typeof import('./src/components/ui/SpeedCard copy.vue')['default']
    ElevationCard: typeof import('./src/components/ui/ElevationCard.vue')['default']
    HeartRateCard: typeof import('./src/components/ui/HeartRateCard.vue')['default']
    IBiCloudArrowUpFill: typeof import('~icons/bi/cloud-arrow-up-fill')['default']
    IBiFileEarmarkText: typeof import('~icons/bi/file-earmark-text')['default']
    IBiupload: typeof import('~icons/bi/upload')['default']
    MetricCard: typeof import('./src/components/ui/MetricCard.vue')['default']
    MinHrComponent: typeof import('./src/components/ui/MinHrComponent.vue')['default']
    PowerCard: typeof import('./src/components/ui/PowerCard.vue')['default']
    RouteMap: typeof import('./src/components/ui/RouteMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedCard: typeof import('./src/components/ui/SpeedCard.vue')['default']
    'SpeedCard copy': typeof import('./src/components/ui/SpeedCard copy.vue')['default']
    TrainingLoadCard: typeof import('./src/components/ui/TrainingLoadCard.vue')['default']
    WeeklyTrainingCard: typeof import('./src/components/ui/WeeklyTrainingCard.vue')['default']
    WeightComponent: typeof import('./src/components/ui/WeightComponent.vue')['default']
  }
}
